task_loader:
  _target_: tasks.UserBehaviorTask
  samples_path: "data/user_behavior_samples.json"
  use_reasoning_in_target: false
  embed_threshold: 0.7
  embed_model: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"


task_name: user_behavior
